repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        pass_filenames: false
      - id: ruff-format
        args: [--check]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        pass_filenames: false
        additional_dependencies:
          - types-networkx
          - pandas-stubs
          - types-seaborn
          - pydot
